# Site settings
title: Det Fælles Designsystem
version: 2.0.0

baseurl: /dkfds-docs

encoding: utf-8

incremental_regeneration_fixer:
  interdependent_files:
#     - "_components/colors/*"
    - "_components/komponenter/form-controls/*"
    - "_components/komponenter/tables/*"
    - "_components/fundament/grids/*"
#     - "_components/form-templates/*"
#     - "_components/typography/*"

#sass:
  #style: compressed
  #load_paths:
  #  - css
  #  - assets/css

collections:
  components:
    output: true
    permalink: /:path/
  pages:
    output: true
    permalink: /:path/
  preview-components:
    output: true
    permalink: /:path/
defaults:
  - scope:
      path: ''
      type: components
    values:
      layout: component
  - scope:
      path: ''
      type: posts
    values:
      layout: post

# Build settings
#markdown: redcarpet
#redcarpet:
#  extensions:
#    - smart
#    - tables
#    - with_toc_data # automatic heading ids

gems:
  - jekyll-redirect-from
  - jekyll-admin

# The site maybe using some static files and they should be copied as-is while building the site. For example images folder. Jekyll has nothing to do with those images. Static files that do not need any Jekyll intervention can be kept as-is using these parameters in the configuration.
keep_files:
  - _includes/code/components
  - assets/img
  - assets/fonts
  - img

exclude:
  - ".ruby-version"
  - ".sass-cache"
  - ".github"
  - ".vscode"
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - config
  - docs
  - vendor
  - manifest.yml
  - node_modules
  - package.json
  - gulpfile.js
  - circle.yml
  - javascript #dont watch for changes in javascript folder and scss, webpack handles this...
  - scss
  - webpack.config.js
  - postcss.config.json
  - examples